In [ ]:
"""@Author: Abhilash Meher
 @Date: 14-11-2022 10:00AM @Last Modified by: Abhilash Meher
  @Last Modified time: 14-11-2022 01:00PM @Title : NumPy Problems
"""

In [1]:
import numpy as np

1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array

In [2]:

arr = np.array([12.23, 13.32, 100, 36.32])
print(arr)

[ 12.23  13.32 100.    36.32]


2. Create a 3x3 matrix with values ranging from 2 to 10.

In [3]:
a=[2,3,4]
b=[5,6,7]
c=[8,9,10]

arr = np.array([a,b,c])
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]


In [21]:
arr = np.zeros(10)
print(arr)
arr[6] = 11
print("Updated 6th value to 11 : ")
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated 6th value to 11 : 
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]


In [5]:
arr = np.arange(12,38)
print("Original Array : ")
print(arr)
print("Reverse Array : ")
print(arr[::-1])

Original Array : 
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse Array : 
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.

In [3]:
arr = np.ones([5,5])
print("Original Array : ")
print(arr)
arr[1:-1]=0
print("\nExpected Ouput : ")
print(arr)

Original Array : 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Expected Ouput : 
[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array.

In [7]:
arr = np.ones((3,3))
print("Original array:")
print(arr)
arr = np.pad(arr,1,'constant', 
                 constant_values=(0))
print("0 on the border and 1 inside in the array")
print(arr)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [10]:
arr = np.zeros((8,8))
print(arr)
print("\nExpected array\n")
arr[1::2,::2] = 1
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

Expected array

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


8. Write a Python program to convert a list and tuple into arrays.

In [9]:
list = [1,2,3,4,5,6,7,8]
tuple_ele = ([8,4,6],[1,2,3])
list_to_arr = np.array(list)
tuple_to_arr = np.array(tuple_ele)
print("List to array : \n")
print(list_to_arr)
print("\nTuple to array : \n")
print(tuple_to_arr)

List to array : 

[1 2 3 4 5 6 7 8]

Tuple to array : 

[[8 4 6]
 [1 2 3]]


9. Write a Python program to append values to the end of an array

In [10]:
arr = np.array([10,20,30])
print("Old Array : ")
print(arr)
arr2 = np.array([30,40,50,60,70,80,90])
new_arr = np.append(arr , arr2)
print("New Array : ")
print(new_arr)

Old Array : 
[10 20 30]
New Array : 
[10 20 30 30 40 50 60 70 80 90]


10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.


In [11]:
complex_list =  [1.00000000 + 0.j , 0.70710678 + 0.70710678j]
comple_arr = np.array(complex_list)
real_arr = []
img_arr = []
for i in comple_arr:
    real_arr.append(i.real)
    img_arr.append(i.imag)
print("Real part of Array : ")
print(np.array(real_arr))
print("Imaginary part of Array : ")
print(np.array(img_arr))

Real part of Array : 
[1.         0.70710678]
Imaginary part of Array : 
[0.         0.70710678]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.


In [12]:
arr = np.array([1,2,3])
print(f"Size of the array : {arr.size}")
print(f"Length of one array element in bytes : {arr.itemsize}")
print(f"Total bytes consumed by the elements of the array : {arr.nbytes}")

Size of the array : 3
Length of one array element in bytes : 4
Total bytes consumed by the elements of the array : 12


12. Write a Python program to find common values between two arrays.

In [13]:
arr1 =  np.array([0,10,20,40,60])
arr2 = [10, 30, 40]

common_ele = np.intersect1d(arr1,arr2)
print(f"Common element between {arr1} and {arr2} are : {common_ele}")

Common element between [ 0 10 20 40 60] and [10, 30, 40] are : [10 40]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2

In [14]:
arr1 =  np.array([ 0, 10, 20, 40, 60, 80 ])
arr2 = np.array([10, 30, 40, 50, 70])

diff_arr = np.setdiff1d(arr1,arr2)
print(f"Set difference between {arr1} and {arr2} are : {diff_arr}")

Set difference between [ 0 10 20 40 60 80] and [10 30 40 50 70] are : [ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays

In [15]:
arr1 =  np.array([ 0, 10, 20, 40, 60, 80 ])
arr2 = np.array([10, 30, 40, 50, 70])

diff_arr = np.setxor1d(arr1,arr2)
print(f"Set exclusive or between {arr1} and {arr2} are : {diff_arr}")

Set exclusive or between [ 0 10 20 40 60 80] and [10 30 40 50 70] are : [ 0 20 30 50 60 70 80]


15. Write a Python program compare two arrays using numpy.
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]


In [11]:
a = np.array([1,2] )
b = np.array([4,5] )

print("a > b")
print(np.greater(a, b))
 
print("a >= b")
print(np.greater_equal(a, b))
 
print("a < b")
print(np.less(a, b))
 
print("a <= b")
print(np.less_equal(a, b))

a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


16. Write a Python program to save a NumPy array to a text file.

In [12]:
arr = np.array([1,2,3,4,5])
with open("text.txt","w") as f:
    f.write(str(arr))
with open("text.txt","r") as f:
    content = f.read()  
print("\nContent in text.txt:\n", content)

np.savetxt("text1.txt", arr)
content = np.loadtxt("text1.txt")
print("\nContent in text1.txt:\n", content)


Content in text.txt:
 [1 2 3 4 5]

Content in text1.txt:
 [1. 2. 3. 4. 5.]


17. Write a Python program to create a contiguous flattened array.


In [13]:
arr = np.array([[[10, 20, 30],[20, 40, 50]]])
print(arr)
flattened_arr = np.ravel(arr)
print(f"\nFlattened array: {flattened_arr}")

[[[10 20 30]
  [20 40 50]]]

Flattened array: [10 20 30 20 40 50]


18. Write a Python program to change the data type of an array.


In [14]:
arr = np.array([[2, 4, 6],[6, 8, 10]])
print(arr)
print(f"Data type of the array is: {arr.dtype}")
print("\nNew Type: float64")
arr = arr.astype('float')
print(arr)

[[ 2  4  6]
 [ 6  8 10]]
Data type of the array is: int32

New Type: float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


19. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.
Expected Output:
[[ 1. 0. 0.]
[ 0. 1. 0.]
[ 0. 0. 1.]]


In [15]:
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


20. Write a Python program to create an array which looks like below array.
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]
[ 1. 1. 1.]]

In [23]:
arr = np.ones([4,3])
arr = np.tril(arr)
print(arr)

[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]


21. Write a Python program to concatenate two 2-dimensional arrays.
Expected Output:
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]
Expected Output:
[[ 0 1 3 0 2 4]
[ 5 7 9 6 8 10]]

In [25]:
arr1 = np.array([[0, 1, 3], [5, 7, 9]] )
arr2 = np.array([[0, 2, 4], [6, 8, 10]] )
new_arr = np.concatenate((arr1,arr2) , axis = 1)
print(new_arr)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


22. Write a Python program to make an array immutable (read-only).

In [26]:
arr = np.array((1,2,3,4,5),dtype=int)
arr.flags.writeable = False
print(arr)
arr[0] = 9
print(arr)

[1 2 3 4 5]


ValueError: assignment destination is read-only

23. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.


In [27]:
arr = np.arange(12).reshape(3,4)
number = 3
arr = arr * number
print(arr)

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


24. Write a Python program to convert a NumPy array into Python list structure.

In [28]:
numpy_arr  = np.arange(0,6).reshape(3,2)
print("Original array elements : ")
print(numpy_arr)
list = numpy_arr.tolist()
print("Array to list : ")
print(list)

Original array elements : 
[[0 1]
 [2 3]
 [4 5]]
Array to list : 
[[0, 1], [2, 3], [4, 5]]


25. Write a Python program to convert a NumPy array into Python list structure.

In [29]:
arr = np.array([ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,
0.35399976, 0.99469633, 0.0694458, 0.54711478])
print("Original Array Elements : ")
print(arr)
print("Array with precision value 3 : ")
np.set_printoptions(precision = 3 ,suppress=True)
print(arr)

Original Array Elements : 
[0.26153123 0.52760141 0.5718299  0.5927067  0.7831874  0.69746349
 0.35399976 0.99469633 0.0694458  0.54711478]
Array with precision value 3 : 
[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


26. Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.


In [30]:
arr = np.array([ 1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01])
print("Original Array Elements : ")
print(arr)
print("Array with precision value 3 : ")
np.set_printoptions(precision = 3 ,suppress=True)
print(arr)

Original Array Elements : 
[   0.       1.6   1200.       0.235]
Array with precision value 3 : 
[   0.       1.6   1200.       0.235]


27. Write a Python program to how to add an extra column to an numpy array

In [31]:
arr = np.array([[ 10, 20, 30],[ 40, 50, 60 ]])
print("Original array : ")
print(arr)
new_array = np.array([[100],[200]])
arr = np.column_stack((arr, new_array))
print("Array after adding column : ")
print(arr)

Original array : 
[[10 20 30]
 [40 50 60]]
Array after adding column : 
[[ 10  20  30 100]
 [ 40  50  60 200]]


28. Write a Python program to remove specific elements in a numpy array.


In [32]:
arr = np.array([ 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("Original Array :")
print(arr)
arr = np.delete(arr, [0,4])
print("After deleting first and fifth element : ")
print(arr)

Original Array :
[ 10  20  30  40  50  60  70  80  90 100]
After deleting first and fifth element : 
[ 20  30  40  60  70  80  90 100]
